server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankingsystem
    username: root
    password: 1234112
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
   name: AUTH-SERVICE 
jwt:
  secret: abcdefghij 
